deployments:
    deploymentGating:
    enabled: true # to enable the feature
    retry: 75 # run poll action 75 times
    sleep: 15 # wait 15 seconds between each poll
    environments: # select the environments you'd like to use with this feature
    - Production
  services:
    ids:
    - b:YXJpOmNsb3VkOmdyYXBoOjpzZXJ2aWNlL2NjNTc4MmI1LWMyNTgtNDdmYS1iNjhkLWI0YjY1NDI1Y2VlNy8zNzM2MWEwZS1hNWJmLTExZWYtOWYwYy0xMjAxZjE2ZWQ0MWY=
