name: Deployment

on:
  push:
    branches:
      - main

jobs:
  build-environment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Run a one-line script
        run: echo starting build

  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: Development
      url: "https://dev.example.com"
    needs: build-environment
    steps:
      - uses: actions/checkout@v2
    
      - name: Deploy to Development
        run: echo Deploying to Development

  deploy-prd:
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: "https://prod.example.com"
    needs: deploy-dev
    steps:
      - name: Deploy to Production
        run: echo Deploying to Production
